Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -441,6 +441,11 @@ fi
 
 # echo "LD_LIBRARY_PATH set to: $LD_LIBRARY_PATH"
 
+if [ -z "$BUILDPACK_REPOSITORY_USERNAME" ]; then
+    echo "Error: BUILDPACK_REPOSITORY_USERNAME environment variable is not set."
+    exit 1
+fi
+
 repositoryUsername=$BUILDPACK_REPOSITORY_USERNAME
 repositoryPassword=$BUILDPACK_REPOSITORY_PASSWORD
 
@@ -456,10 +461,8 @@ authJson=$(cat <<-END
 END
 )
 
-composerDir="$build_dir/.composer"
-mkdir -p "$composerDir"
-authFile="$composerDir/auth.json"
-echo "$authJson" > "$authFile"
+mkdir -p $build_dir/.composer
+echo "$authJson" > $build_dir/.composer/auth.json
 
 # reset $COMPOSER for the platform install step
 COMPOSER_bak="$COMPOSER"
