Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -441,6 +441,10 @@ fi
 
 # echo "LD_LIBRARY_PATH set to: $LD_LIBRARY_PATH"
 
+if [ -z "$BUILDPACK_REPOSITORY_PASSWORD" ]; then
+    echo "Error: BUILDPACK_REPOSITORY_PASSWORD environment variable is not set."
+    exit 1
+fi
 if [ -z "$BUILDPACK_REPOSITORY_USERNAME" ]; then
     echo "Error: BUILDPACK_REPOSITORY_USERNAME environment variable is not set."
     exit 1
